[build]
builder = "nixpacks"

[deploy]
startCommand = "alembic upgrade head && gunicorn run:app --workers 2 --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker"
healthcheckPath = "/health"
